# Generated by Django 3.1.7 on 2021-07-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='author',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(max_length=50),
        ),
    ]
