# Generated by Django 3.1.7 on 2021-07-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizes', '0002_auto_20210720_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='no_of_questions',
            field=models.IntegerField(default=10),
        ),
    ]
